
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 13 00:03:14 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 14;
  public static final int READ = 6;
  public static final int IDENT = 27;
  public static final int SEMICOLON = 18;
  public static final int PLUS = 10;
  public static final int RBRACE = 25;
  public static final int RPAREN = 21;
  public static final int FINDANY = 8;
  public static final int CHAR = 28;
  public static final int RANGLE = 23;
  public static final int MINUSMINUS = 17;
  public static final int LBRACE = 24;
  public static final int LPAREN = 20;
  public static final int COMMA = 19;
  public static final int LANGLE = 22;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int PROG = 2;
  public static final int PLUSPLUS = 16;
  public static final int MINUS = 11;
  public static final int CONST = 3;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int DOT = 9;
  public static final int ASSIGN = 15;
  public static final int NEW = 4;
  public static final int BOOL = 29;
  public static final int MUL = 12;
  public static final int VOID = 7;
}

